apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipeline-httpserver-app
  labels:
    app: pipeline-httpserver
    version: stable
spec:
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: pipeline-httpserver
      version: stable
  template:
    metadata:
      labels:
        app: pipeline-httpserver
        version: stable
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:22"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.port }}
