apiVersion: v1
description: A Helm chart for httpserver
name: pipeline-httpserver
version: 0.0.2
appVersion: 1.0.2
home: https://github.com/satomic/pipeline-example-python
icon: https://camo.githubusercontent.com/1e11d429705bf6695b79d24966cb1267c00b7df6/68747470733a2f2f7777772e646f636b65722e636f6d2f73697465732f64656661756c742f66696c65732f6f79737465722d72656769737472792d332e706e67
sources:
  - https://github.com/satomic/pipeline-example-python
maintainers:
  - name: satomic
    email: xuefeng@rancher.com
